version: "3.9"

volumes:
  dev_postgres_data: {}
  dev_postgres_data_backups: {}
  dev_mailhog_data: {}

services:
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data:Z
      - dev_postgres_data_backups:/backups:z
    ports:
      - "5432:5432"
  mailhog:
    image: mailhog/mailhog:v1.0.0
    user: root
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - dev_mailhog_data:/maildir
    ports:
      - "1025:1025"
      - "8025:8025"
  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A config worker -l INFO
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=psql://postgres:postgres@db:5432/postgres
      - EMAIL_URL=smtp://mailhog:1025
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  assets:
    build:
      context: .
      dockerfile: Dockerfile.assets
    volumes:
      - ./assets:/code/assets
      - ./static/dist:/code/static/dist
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=psql://postgres:postgres@db:5432/postgres
      - EMAIL_URL=smtp://mailhog:1025
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
