FROM python:3.9-slim-buster

# Set environment variables
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV DJANGO_SETTINGS_MODULE config.settings.development

# Install system dependencies
COPY ./scripts/apt.sh /apt.sh
RUN /apt.sh

# Install Python dependencies
COPY ./requirements /requirements
RUN pip install -r /requirements/dev.txt

# Set work directory
WORKDIR /code

# Copy project
COPY . /code/

CMD [ "python", "manage.py", "runserver" ]
