version: "3.9"

volumes:
  static_volume: {}

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  nginx:
    image: rahmanfadhil/websitex-nginx:latest
    build:
      context: ./docker/nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
  celery:
    image: rahmanfadhil/websitex-celery:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: prod-celery
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env.prod
  web:
    image: rahmanfadhil/websitex-web:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: prod-web
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env.prod
    volumes:
      - static_volume:/code/staticfiles
