version: "3.9"

volumes:
  dev_postgres_data: {}
  dev_postgres_data_backups: {}
  dev_mailhog_data: {}

services:
  postgres:
    image: postgres:13.4
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data:Z
      - dev_postgres_data_backups:/backups:z
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2.5-alpine
    ports:
      - "6379:6379"
  mailhog:
    image: mailhog/mailhog:v1.0.0
    user: root
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - dev_mailhog_data:/maildir
    ports:
      - "1025:1025"
      - "8025:8025"
  celery:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: "watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A config worker -l INFO --concurrency=2"
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    # Uncomment this line of you want to enable VSCode debugging
    # command: "python -m debugpy --listen 0.0.0.0:9999 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "9999:9999"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
  assets:
    build:
      context: .
      dockerfile: Dockerfile
      target: assets
    volumes:
      - .:/code
