version: "3.9"

volumes:
  dev_postgres_data: {}
  dev_mailhog_data: {}
  dev_media: {}

services:
  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"
  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
  mailhog:
    image: mailhog/mailhog:v1.0.0
    user: root
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - dev_mailhog_data:/maildir
    ports:
      - "1025:1025"
      - "8025:8025"
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/code
      - dev_media:/media
      - /code/node_modules
    ports:
      - "8000:8000"
      - "9999:9999"
      - "5173:5173"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
